[project]
name = "bogodb"
version = "0.1.0"
description = "Random-Walk Graph Database Challenge"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20.0",
    "tqdm>=4.60.0",
    "matplotlib>=3.5.0",
]

[tool.uv]
dev-dependencies = []